language: node_js
node_js:
- '0.10'
before_script:
- psql -c 'create database valet_io_pledge;' -U postgres
- gulp migrate
env:
  global:
  - secure: HQJyiIck8D3KPE5IKwrowrV8aZn80O+hEW02xyLhezYHTJ/Az8hxujH2VgT9StpQGGiI838yjKiqIWfJYbR17A1VMSxWbDnwN62H5RYpJvyWwJpk91f1qayTj0pWZVNsCUNkQ+bPP1a/yhrs2wIJ0kQc96fddMPaXrlsc61Qh8U=
  - database__connection__database=valet_io_pledge database__connection__username=postgres
deploy:
- provider: heroku
  app: valet-io-pledge-dev
  api_key:
    secure: v6aol/bx1rzv2a8DzDwOaQzVO8NlgbN4NAEWPowHfgwlL/ahdLO/x7P5YeLMKLiS5EJKoV8hiVLxpEN4SUlIq0VK9+7Ve0LyQoZVv7mkBxetFuM92C69hQvuwZfALLo7H+nN4I9Qd5bKURUNctPRJZ3rcZ6yehtDnqL5mbKOorI=
  on:
    branch: master
    repo: valet-io/pledge-api
  run:
  - npm run migrate
- provider: heroku
  app: valet-io-pledge-staging
  api_key:
    secure: v6aol/bx1rzv2a8DzDwOaQzVO8NlgbN4NAEWPowHfgwlL/ahdLO/x7P5YeLMKLiS5EJKoV8hiVLxpEN4SUlIq0VK9+7Ve0LyQoZVv7mkBxetFuM92C69hQvuwZfALLo7H+nN4I9Qd5bKURUNctPRJZ3rcZ6yehtDnqL5mbKOorI=
  on:
    branch: master
    repo: valet-io/pledge-api
  run:
  - npm run migrate
- provider: heroku
  app: valet-io-pledge
  api_key:
    secure: v6aol/bx1rzv2a8DzDwOaQzVO8NlgbN4NAEWPowHfgwlL/ahdLO/x7P5YeLMKLiS5EJKoV8hiVLxpEN4SUlIq0VK9+7Ve0LyQoZVv7mkBxetFuM92C69hQvuwZfALLo7H+nN4I9Qd5bKURUNctPRJZ3rcZ6yehtDnqL5mbKOorI=
  on:
    repo: valet-io/pledge-api
    tags: true
    all_branches: true
  run:
  - npm run migrate
addons:
  postgresql: '9.3'
notifications:
  slack:
    secure: ZzSNTvOCbhgU3YZ79SwmZdFsixEcWo4vuYrXrlukt3WhQAs6UGP3L3uekb31NUBgHMoi53q2ZJ3ZJLzwd1QiQbC1zrVZ0NXYj9fjUMErYlYS38LDdcM2FSt4moh+hGwJU6QFiiPnkgZcpkivFF9kUGp1yi8Y8h9ZgAn9VCw9miM=
  email: false
