language: node_js
node_js:
  - '0.10'
before_script:
  - psql -c 'create database valet_io_pledge;' -U postgres
  - gulp migrate
env: database_connection_database=valet_io_pledge database_connection_username=postgres
